version: "3"
services:
  wca_on_rails:
    build:
      context: WcaOnRails
    environment:
      DATABASE_HOST: wca_test_db
      RAILS_ENV: test
    # First, install Ruby and Node dependencies
    # Next, wait for the database to be ready for queries via https://stackoverflow.com/a/53717981/2558618
    # Run the tests
    command: >
      bash -c 'bundle install && yarn install &&
      while ! mysql --host=wca_test_db --user=root -e "SELECT 1" >/dev/null 2>&1; do
        echo "Waiting for MySQL to be ready" && sleep 5 ;
      done &&
      echo "MySQL is ready!" &&
      bin/rails db:environment:set RAILS_ENV=test || true &&
      bin/rake db:reset &&
      bin/rake assets:precompile &&
      bin/rspec'
    volumes:
      - ./WcaOnRails:/app
    tty: true
    depends_on:
      - wca_test_db

  wca_test_db:
    image: mysql:8.0
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "true"
    expose:
      - "3306"
    volumes:
      - wca_test_db_volume:/var/lib/mysql
    # Suppress unneeded messages via https://stackoverflow.com/a/55706057/2558618
    cap_add:
      - SYS_NICE

volumes:
  wca_test_db_volume:
    driver: local
